# These are supported funding model platforms

github: []
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
